config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: 'only one movie/list combination for on bookmark' }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save!
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <%= simple_form_for [@list, @bookmark] do |f|%>
    <%= f.input :comment, placeholder: "Enter a comment about the movie" %>
    <%#= f.input :movie_id, collection: Movie.all %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <div class="navbar-lewagon">
      <div class="logo"> <i class="fa-solid fa-film"></i> </div>
      <div class="links d-flex">
        <div class="px-3"><%= link_to "My lists", lists_path %></div>
        <div class="px-3"><%= link_to "New List", new_list_path %></div>
      </div>
    </div>

    <%= yield %>
  </div>
  </body>
</html>

app/views/lists/index.html.erb
<div class="list-banner card-category" style="background-image: url('<%= cl_image_path("a9asb2eyqjid80i61mda", crop: :fill) %>')">
  <h1>Save any kind of movies</h1>
  <h2>Classic</h2>
</div>

<div class="container d-flex flex-column">
  <div class="d-flex justify-content-between ">
    <h2 class="text-bold">My Lists</h2>
    <button class="btn btn-success text-white" type="submit"><%= link_to "New List", new_list_path %></button>
  </div>
    <ul class="m-1 cards">
      <% @lists.each do |list| %>
        <% image_url = list.photo.present? ? cl_image_path(list.photo.key, height: 100, crop: :fill) : cl_image_path("a9asb2eyqjid80i61mda", crop: :fill) %>
        <li class="card-category" style="background-image: url('<%= cl_image_path(image_url, crop: :fill) %>')">
        <%= link_to list.name, list_path(list) %>
        </li>
      <% end %>
    </ul>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for(@list) do |f| %>
      <%= f.input :name, placeholder: "Drama" %>
      <%= f.input :photo, as: :file %>
      <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="container">


  <% image_url = @list.photo.present? ? cl_image_path(@list.photo.key, height: 100, crop: :fill) : cl_image_path("a9asb2eyqjid80i61mda", crop: :fill) %>
  <div class="list-banner card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_url %>')">

    <h1><%=  @list.name%></h1>
    <%= "You haven't saved any movies yet!" if @list.movies.empty? %>
    <%= link_to "Add a movie to my list",  new_list_bookmark_path(@list) %>
  </div>

    <div class="py-3">
      <% @list.movies.each do |movie| %>
        <div class="d-flex">
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <div> <%= image_tag movie.poster_url, alt: movie.title%></div>
          <h3><%= movie.title %></h3>
          <p><%= movie.rating %></p>
          <p><%= movie.overview %></p>
          <p><%= bookmark.comment %></p>
          <p><%= link_to "delete film", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove #{movie.title} from your #{@list.name} list"}%></p>
        </div>
      <% end %>
    </div>

  </div>

  <div>
    <%= link_to "delete this list", list_path(@list), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this list?" } %>
  </div>
</div>